language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

before_install:
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then sudo apt-get install libsnappy-dev; fi

install:
    - pip install --use-mirrors tox

script: TOXENV=py$(echo $TRAVIS_PYTHON_VERSION | tr -d . | sed 's/pypy/py/g') tox -v
